name: Deploy to GKE via OIDC

on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud via OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure cloud run 
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloud-run-python-app
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloud-run-python-app .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloud-run-python-app
          gcloud services enable run.googleapis.com
          
          
      - name: create-service
        run: |
          gcloud run deploy cloud-run-python-service --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloud-run-python-app --platform managed --region us-central1 --allow-unauthenticated
          
