name: Deploy to Cloudrun via OIDC

on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  deploy-clour-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud via OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      -  name: Authenticate Docker with gcloud
         run: |
          gcloud auth configure-docker us-docker.pkg.dev

      - name: Configure cloud run 
        run: |
          gcloud services enable run.googleapis.com
          gcloud auth configure-docker us-docker.pkg.dev
          docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-python-app/my-app:latest .
          docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-python-app/my-app:latest
          
          
      - name: create-service
        run: |
          gcloud run deploy cloud-run-python-service --image us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-python-app/my-app:latest --platform managed --region us-central1 --allow-unauthenticated
